version: "3.4"

services:
  postgres:
    container_name: DevConnect
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: devConnect
      POSTGRES_PASSWORD: devConnect

volumes:
  postgres_data:
